languageCode = "en"
languageName = "English"
weight = 1
title = "Justin Johnson"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
# logo = "images/headshot.png"
# secondaryLogo = "images/headshot.png"
# description = "My awesome website"
# copyright = "Copy, _right?_ :thinking_face:"

[params.author]
name = "Justin Johnson"
image = "images/headshot.png"
headline = "Engineering Leader"
bio = "I love building APIs, mentoring, and sponsoring the next generation of engineers."
links = [
  { linkedin = "https://www.linkedin.com/in/justinrjohnson/" },
  { github = "https://github.com/booleangate" },
  { stack-overflow = "https://stackoverflow.com/users/126562/justin-johnson" },
  #     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #     { codepen = "https://codepen.io/username" },
  #     { dev = "https://dev.to/username" },
  #     { discord = "https://discord.gg/invitecode" },
  #     { dribbble = "https://dribbble.com/username" },
  #     { gitlab = "https://gitlab.com/username" },
  #     { hashnode = "https://username.hashnode.dev" },
  #     { instagram = "https://instagram.com/username" },
  #     { keybase = "https://keybase.io/username" },
  #     { mastodon = "https://mastodon.instance/@username" },
  #     { medium = "https://medium.com/username" },
  #     { orcid = "https://orcid.org/userid" },
  #     { reddit = "https://reddit.com/user/username" },
  #     { researchgate = "https://www.researchgate.net/profile/username" },
  #     { slack = "https://workspace.url/team/userid" },
  #     { soundcloud = "https://soundcloud.com/username" },
]
